version: '3'


services:
  notebooks:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - docker/notebooks.env
    volumes:
      - ./notebooks:/work/notebooks
    ports:
      - 8888:8888
